name: CI

on: [push, pull_request]

jobs:
  
  build_ps4:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build Files
        run: |
          ./_build.bat
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: RB4DX-1.08-PS4
          path: _build
